### PR TITLE
Fix performance issue

### LINKED ISSUE #172: MOI is slow querying solution information again
I'm getting the same slow performance as in #102 on Cbc 0.8.1 (I'm pretty sure that it was on 0.8.0 too).

```julia
 pkg> add JuMP,Cbc
   Resolving package versions...
  [9961bab8] + Cbc v0.8.1
  [4076af6c] + JuMP v0.21.9

julia> using JuMP, Cbc, BenchmarkTools

julia> function bench(optimizer, N = 30_000)
           model = Model(with_optimizer(optimizer))
           @variable(model, x[i = 1:N] >= i)
           @objective(model, Min, sum(x))
           optimize!(model)
           @benchmark value.($x)
        end
bench (generic function with 2 methods)

julia> bench(Cbc.Optimizer)
Optimal - objective value 4.50015e+08
Optimal objective 450015000 - 0 iterations time 0.002
BenchmarkTools.Trial: 2 samples with 1 evaluation.
 Range (min … max):  4.568 s …   4.631 s  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     4.600 s              ┊ GC (median):    0.00%        
 Time  (mean ± σ):   4.600 s ± 44.846 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

  █                                                       █  
  █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁█ ▁
  4.57 s         Histogram: frequency by time        4.63 s <

 Memory estimate: 8.93 MiB, allocs estimate: 390002.
```

### PR DESCRIPTION
**Pull request by odow**
Closes #172 
Closes #173 

## Before

```Julia
julia> bench();
Optimal - objective value 4.50015e+08
Optimal objective 450015000 - 0 iterations time 0.002
  4.113598 seconds (60.00 k allocations: 2.976 MiB)
```

## After

```Julia
julia> bench();
Optimal - objective value 4.50015e+08
Optimal objective 450015000 - 0 iterations time 0.002
  0.000598 seconds (4 allocations: 234.547 KiB)
```

## Script

```Julia
using Cbc
const MOI = Cbc.MOI

function bench(N = 30_000)
    cbc = Cbc.Optimizer()
    model = MOI.Utilities.CachingOptimizer(MOI.Utilities.Model{Float64}(), cbc)
    x = MOI.add_variables(model, N);
    MOI.add_constraints(model, x, MOI.GreaterThan.(1.0:N));
    MOI.set(model, MOI.ObjectiveSense(), MOI.MIN_SENSE);
    f = MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.(1.0, x), 0.0);
    MOI.set(model, MOI.ObjectiveFunction{typeof(f)}(), f);
    MOI.optimize!(model)
    @time MOI.get.(model, MOI.VariablePrimal(), x)
end
bench()
```

### CODE REVIEW

File: src/MOI_wrapper/MOI_wrapper.jl [hunk 1]
```diff
@@ -776,46 +771,51 @@ function MOI.get(model::Optimizer, ::MOI.RelativeGap)
...
-    return _unsafe_wrap_cbc_array(
-        model,
-        Cbc_getColSolution,
-        Cbc_getNumCols(model),
-        x.value,
-    )
+_update_cache(::Optimizer, data::Vector{Float64}, ::Any, ::Any) = data
+
+function _update_cache(model::Optimizer, ::Nothing, f_p::F, f_n::G) where {F,G}
+    p = f_p(model)
```
Comment (blegat) [inline src/MOI_wrapper/MOI_wrapper.jl:777]: Couldn't you skip this if `variable_primal` is not `nothing` ? And then you reset it to `nothing` when `optimize!` is called.

Comment (odow) [reply src/MOI_wrapper/MOI_wrapper.jl:779]: See line 774, we do skip it.

**Review by blegat — APPROVED** [review]
